version: str()
title: str()
description: str()
parameters: list(include('parameter'))
pipeline: list(include('operator'))
---
parameter:
  name: str()
  label: str()
  description: str()
  type: str()
  valid_values: list()

operator:
  id: str()
  type: str()
  include: list(required=False)
  start_at: str(required=False)
  labels:
    log_type: str(required=False)
    plugin_id: str(required=False)
  output: str()
  regex: str(required=False)
  timestamp:
    parse_from: str(required=False)
    layout: str(required=False)
  severity:
    parse_from: str(required=False)
    preset: str(required=False)
    mapping:
      info: str(required=False)
      error: str(required=False)
      warning: str(required=False)
      critical: str(required=False)
      debug: str(required=False)
      trace: str(required=False)
      alert: str(required=False)
      emergency: str(required=False)
      catastrophe: str(required=False)
    preserve_to: str(required=False)
    if: str(required=False)
# name: str()
# age: int(max=200)
# height: num()
# awesome: bool()
