name: Validate YAML
on: [push]
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "jsirianni/stanza"
        version: "latest"
        file: "stanza_linux_amd64"
        target: "stanza"
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: whoami
    - run: ls -la
    - run: chmod +x ./stanza
    - run: ./stanza --validate
