name: Validate YAML
on: [push]
jobs:
  ValidateYaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nrkno/yaml-schema-validator-github-action@master
      with:
        schema: 'schemas/aerospike.yaml'
        target: 'plugins/aerospike.yaml'
