name: Validate YAML
on: [push]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "jsirianni/stanza"
        version: "tags/v0.14.2-jsirianni"
        file: "stanza_linux_amd64"
        target: "stanza"
        token: ${{ secrets.GITHUB_TOKEN }}
