name: Validate YAML
on: [push]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Stanza
      uses: jaxxstorm/action-install-gh-release@release/v1-alpha
      with: # Grab a specific tag
        repo: observiq/stanza
