name: Validate YAML
on: [push]
jobs:
  ValidateYaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validating Plugin Yaml
      run: ./schema.sh
    - name: Validate Plugin Pipelines
      run: make test